[build]
  publish = "_site"
  command = "npm run build"
	functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  # Serve a full size version
  from = "/images/full/:file"
  to = "/.netlify/images?url=/images/:file"
  status = 200

[[redirects]]
  # ...or serve a resized version
  from = "/images/:width/:file"
  to = "/.netlify/images?url=/images/:file&width=:width"
  status = 200